#[[main]]
#    name = "Blog"
#    url = "/posts/"
#    weight = 1

[[main]]
    name = "Episoden"
    url = "/podcast"
    weight = 1

#[[main]]
#    name = "About"
#    url = "/about"
#    weight = 4